# Stripe Configuration
[stripe]
secret_key = "sk_test_your_test_key"  # Replace with your actual Stripe secret key
public_key = "pk_test_your_test_key"  # Replace with your actual Stripe public key
webhook_secret = "whsec_your_webhook_secret"  # Replace with your actual webhook secret

# Price IDs for subscription plans
basic_price_id = "price_basic_test"
pro_price_id = "price_pro_test"

# Base URL for the application
base_url = "http://localhost:8501" 